# Site settings
title: PowerAppMaker.Dev
email: james.hawkins@snolab.ca
description: >
  Follow a struggling Power App Maker on my journey to become a Power App expert. From beginner to pro, I share my successes and failures, offer advice and provide resources to help other would-be Power App Makers on their journeys.
baseurl: ""
url: "https://www.powerappmaker.dev"

# Social
githubUsername: jhawksno

# Build settings
markdown: kramdown

#themeColor: purple # green, blue, orange, purple, grey
# This is will eventually be removed and reference the updated theme
fixedNav: "false" # true or false
themeColor: purple

# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html
include: [_pages]
exclude: [_site, CHANGELOG.md, LICENSE, README.md]
sass:
  style: compressed

plugins:
  - jekyll-paginate-v2

# Pagination Settings
pagination:
  enabled: true
  per_page: 3
  #permalink: '/page/:num/'
  title: " - page :num"
  limit: 0
  sort_field: "date"
  sort_reverse: true
